### ISSUE TITLE
Implementar placeholder/string no módulo external database

### ISSUE THREAD

**Issue by aldo774** [multidadosti-erp/server-tools#3]
Implementar placeholder/string ao field *Caracter de conexão* no módulo external database atrelado a evento onchange com dependência com o field *Conector*(Dependendo do valor setado em *conector*, atribuir ao campo de *Carater de conexão* o padrão correspondente)

**Comment by mstuttgart** [comment]
PR: https://github.com/OCA/server-tools/pull/661

**Comment by rodrigets** [comment]
Módulo original foi refatorado.
